// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.baulsupp.cooee.p.GoogleTokenExchangeRequest in api.proto
package com.baulsupp.cooee.p

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class GoogleTokenExchangeRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  @JvmField
  public val idToken: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
  )
  @JvmField
  public val authCode: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GoogleTokenExchangeRequest, GoogleTokenExchangeRequest.Builder>(ADAPTER, unknownFields)
    {
  public override fun newBuilder(): Builder {
    val builder = Builder()
    builder.idToken = idToken
    builder.authCode = authCode
    builder.addUnknownFields(unknownFields)
    return builder
  }

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GoogleTokenExchangeRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (idToken != other.idToken) return false
    if (authCode != other.authCode) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + idToken.hashCode()
      result = result * 37 + (authCode?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """idToken=${sanitize(idToken)}"""
    if (authCode != null) result += """authCode=${sanitize(authCode)}"""
    return result.joinToString(prefix = "GoogleTokenExchangeRequest{", separator = ", ", postfix =
        "}")
  }

  public fun copy(
    idToken: String = this.idToken,
    authCode: String? = this.authCode,
    unknownFields: ByteString = this.unknownFields,
  ): GoogleTokenExchangeRequest = GoogleTokenExchangeRequest(idToken, authCode, unknownFields)

  public class Builder : Message.Builder<GoogleTokenExchangeRequest, Builder>() {
    @JvmField
    public var idToken: String = ""

    @JvmField
    public var authCode: String? = null

    public fun idToken(idToken: String): Builder {
      this.idToken = idToken
      return this
    }

    public fun authCode(authCode: String?): Builder {
      this.authCode = authCode
      return this
    }

    public override fun build(): GoogleTokenExchangeRequest = GoogleTokenExchangeRequest(
      idToken = idToken,
      authCode = authCode,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GoogleTokenExchangeRequest> = object :
        ProtoAdapter<GoogleTokenExchangeRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      GoogleTokenExchangeRequest::class, 
      "type.googleapis.com/com.baulsupp.cooee.p.GoogleTokenExchangeRequest", 
      PROTO_3, 
      null, 
      "api.proto"
    ) {
      public override fun encodedSize(`value`: GoogleTokenExchangeRequest): Int {
        var size = value.unknownFields.size
        if (value.idToken != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.idToken)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.authCode)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: GoogleTokenExchangeRequest): Unit {
        if (value.idToken != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.idToken)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.authCode)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: GoogleTokenExchangeRequest):
          Unit {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.authCode)
        if (value.idToken != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.idToken)
      }

      public override fun decode(reader: ProtoReader): GoogleTokenExchangeRequest {
        var idToken: String = ""
        var authCode: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> idToken = ProtoAdapter.STRING.decode(reader)
            2 -> authCode = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GoogleTokenExchangeRequest(
          idToken = idToken,
          authCode = authCode,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: GoogleTokenExchangeRequest): GoogleTokenExchangeRequest =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
